builds:
  - main: ./cmd/buffalo/main.go
    binary: buffalo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/thegodwinproject/cli/internal/runtime.Version={{ .Tag }}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - name_template: "buffalo_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      '386': i386
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: 'buffalo'
    tap:
      owner: 'thegodwinproject'
      name: 'homebrew-tap'
    install: |
      bin.install "buffalo"

dockers:
  - 
    image_templates:
      - thegodwinproject/buffalo:{{ .Tag }}
      - thegodwinproject/buffalo:latest
    dockerfile: 'Dockerfile.build'
    goos: linux
    goarch: amd64
    use: docker

  - 
    image_templates:
      - thegodwinproject/buffalo:{{ .Tag }}-slim
      - thegodwinporject/buffalo:latest-slim
    dockerfile: 'Dockerfile.slim.build'
    goos: linux
    goarch: amd64
    use: docker

